# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            CCTV Control in Seattle
tagline:          ''
description:      'A Project about CCTV impact on crime and privacy in Seattle' 
url:              "https://jianit.github.io"
baseurl:          "/SOC401-DS-AI-lab"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://jianit.github.io/SOC401-DS-AI-lab/
